### ISSUE TITLE
Error problem: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by akhsassoualid** [KacperKubara/heterogeneous_dist_metrics#7]
Hello Kacper, 
First, thank you for developing this package, it's been three days that I am looking for a solution to find a distance in terms of mixed data.
Well, I just tested distython on my data, which is made up of 8 categorical variables and 12 continuous variables, I used LabelEncoder, and I converted the data to numpy.array, but HEOM() still shows me the following error: 
Traceback (most recent call last):

  File "<ipython-input-26-14fa450dc942>", line 2, in <module>
    heom_metric = HEOM(DF, [1,2,3,4,5,6,7,8,9])

  File "C:\Users\admin\Anaconda3\lib\site-packages\distython\HEOM.py", line 35, in __init__
    self.range = np.nanmax(X, axis = 0) - np.nanmin(X, axis = 0)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by KacperKubara** [comment]
Hey,
Apologies for the late reply. I presume that you fixed that problem since you closed that issue?
It seems like you either didn't convert the Dataframe to Numpy array, or you forgot to convert a column with a string data to label encoded equivalent. Could you let me know what was the issue? It might be useful for other people who encounter this problem asw well!
Best,
Kacper
P.S. There is updated code in dev branch, I will aim to update the master by the end of this week.
